name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.4

      - name: Install Dependencies
        run: |
          haxe -version
          haxelib install --always js.hxml
          haxelib git deepnightLibs https://github.com/deepnight/deepnightLibs.git
          haxelib git heaps https://github.com/HeapsIO/heaps.git
          haxelib list

      - uses: actions/checkout@v2

      - name: Build Javascript Target
        run: haxe js.hxml

