name: CI

on:
  push:
    branches: [ master, ShipBuilding ]
  pull_request:
    branches: [ master, ShipBuilding ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.4
      - name: Install Dependencies
        run: |
          sudo apt-get install lame
          haxe -version
          haxelib install --always js.hxml
          haxelib git deepnightLibs https://github.com/deepnight/deepnightLibs.git
          haxelib git heaps https://github.com/HeapsIO/heaps.git
          haxelib git box2d https://github.com/openfl/box2d.git
          haxelib list
      - name: Build Javascript Target
        run: haxe js.hxml
